# Generated by Django 5.2 on 2025-04-25 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupe',
            name='biography',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupe',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('SP', 'Synth Pop'), ('AR', 'Alternative Rock')], default='HH', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupe',
            name='official_home_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupe',
            name='year_formed',
            field=models.IntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2025)]),
            preserve_default=False,
        ),
    ]
