# Generated by Django 5.2 on 2025-04-25 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_groupe_active_groupe_biography_groupe_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('Disques', 'Records'), ('Vetements', 'Clothing'), ('Affiches', 'Posters'), ('Divers', 'Miscellaenous')], default='Divers', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2025)]),
            preserve_default=False,
        ),
    ]
